### ISSUE TITLE
Changing username & password

### ISSUE THREAD

**Issue by jesydeepu** [mazemax/tboholidays-php#2]
How can i change the username, password to the one provided to me by tbo as Test Server API credentials. When i change username , password to the one provided by tbo it shows error. ### **Is there any other modifications to be done to use these files.?**
When i use 
/* Travel Agent Credentials */
		$username = "kuldeepapi";
		$password = "12345";
		/* Travel Agent Credentials */
But when i change username , password ,
**It shows error as below:**
 Fatal error: Uncaught SoapFault exception: [HTTP] Error Fetching http headers in /home/marginfi/public_html/marginfix.net/vendor/zendframework/zend-soap/src/Client.php:1033 Stack trace: #0 [internal function]: SoapClient->__doRequest('<?xml version="...', 'http://api.tbot...', 'http://TekTrave...', 1, 0) #1 /home/marginfi/public_html/marginfix.net/vendor/zendframework/zend-soap/src/Client.php(1033): call_user_func(Array, '<?xml version="...', 'http://api.tbot...', 'http://TekTrave...', 1, 0) #2 /home/marginfi/public_html/marginfix.net/example-client.php(15): Zend\Soap\Client->_doRequest(Object(Zend\Soap\Client\Common), '<?xml version="...', 'http://api.tbot...', 'http://TekTrave...', 1, 0) #3 [internal function]: TBOSOAPClient->_doRequest(Object(Zend\Soap\Client\Common), '<?xml version="...', 'http://api.tbot...', 'http://TekTrave...', 1, 0) #4 /home/marginfi/public_html/marginfix.net/vendor/zendframework/zend-soap/src/Client/Common.php(55): call_user_func(Array, Object(Zend\Soap\Client\Common), '<?xml version="...', 'htt in /home/marginfi/public_html/marginfix.net/vendor/zendframework/zend-soap/src/Client.php on line 1033

**Comment by mazemax** [comment]
At the time when I wrote this code, there were no additional fields required other than the Travel Agent Credentials you have mentioned above. Perhaps you can email TBO support team for username, password issue. 
**Tip:** Initially use SoapUI to test SOAP API calls.
_Ref:_ https://www.soapui.org/
