### ISSUE TITLE
HotelSearch

### ISSUE THREAD

**Issue by mshoaibdev** [mazemax/tboholidays-php#3]
Hello, thanks for the APi , I'm facing an issue when i call searchHotels method the error shows up, however other methods working fine. can you look into this please.

`Uncaught SoapFault exception: [a:InternalServiceFault] Error in deserializing body of request message for operation 'HotelSearch'.`

**Comment by mazemax** [comment]
As stated in error message the deserialization is not done correctly. Sample code with this error is required to replicate this issue.
