### ISSUE TITLE
Fatal error: Uncaught SoapFault

### ISSUE THREAD

**Issue by kyamasam** [mazemax/tboholidays-php#5]
Fatal error: Uncaught SoapFault: SOAP-ERROR: Parsing WSDL: Couldn't load from 'http://api.tbotechnology.in/HotelAPI_V7/HotelService.svc?wsdl=wsdl0' : failed to load external entity "http://api.tbotechnology.in/HotelAPI_V7/HotelService.svc?wsdl=wsdl0" in

**Comment by mazemax** [comment]
You can use newer WSDL file from TBO website to regenerate classes using Wsdl2PhpGenerator in index.php
